name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      # Build for Chrome
      - name: Build for Chrome
        run: bun run build

      - name: Zip for Chrome
        run: bun run zip

      # Build for Firefox
      - name: Build for Firefox
        run: bun run build:firefox

      - name: Zip for Firefox
        run: bun run zip:firefox

      - name: Create Release
        run: gh release create $GITHUB_REF_NAME --generate-notes .output/find-in-anki-*-chrome.zip .output/find-in-anki-*-firefox.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
